// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: cotune.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request messages
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_cotune_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{0}
}

type PeerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"` // "json" or "proto"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfoRequest) Reset() {
	*x = PeerInfoRequest{}
	mi := &file_cotune_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoRequest) ProtoMessage() {}

func (x *PeerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoRequest.ProtoReflect.Descriptor instead.
func (*PeerInfoRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{1}
}

func (x *PeerInfoRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*ConnectRequest_Multiaddr
	//	*ConnectRequest_PeerInfo
	Target        isConnectRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_cotune_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetTarget() isConnectRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ConnectRequest) GetMultiaddr() string {
	if x != nil {
		if x, ok := x.Target.(*ConnectRequest_Multiaddr); ok {
			return x.Multiaddr
		}
	}
	return ""
}

func (x *ConnectRequest) GetPeerInfo() *PeerInfo {
	if x != nil {
		if x, ok := x.Target.(*ConnectRequest_PeerInfo); ok {
			return x.PeerInfo
		}
	}
	return nil
}

type isConnectRequest_Target interface {
	isConnectRequest_Target()
}

type ConnectRequest_Multiaddr struct {
	Multiaddr string `protobuf:"bytes,1,opt,name=multiaddr,proto3,oneof"`
}

type ConnectRequest_PeerInfo struct {
	PeerInfo *PeerInfo `protobuf:"bytes,2,opt,name=peer_info,json=peerInfo,proto3,oneof"`
}

func (*ConnectRequest_Multiaddr) isConnectRequest_Target() {}

func (*ConnectRequest_PeerInfo) isConnectRequest_Target() {}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MaxResults    int32                  `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_cotune_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type SearchProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctid          string                 `protobuf:"bytes,1,opt,name=ctid,proto3" json:"ctid,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProvidersRequest) Reset() {
	*x = SearchProvidersRequest{}
	mi := &file_cotune_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProvidersRequest) ProtoMessage() {}

func (x *SearchProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProvidersRequest.ProtoReflect.Descriptor instead.
func (*SearchProvidersRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{4}
}

func (x *SearchProvidersRequest) GetCtid() string {
	if x != nil {
		return x.Ctid
	}
	return ""
}

func (x *SearchProvidersRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctid          string                 `protobuf:"bytes,1,opt,name=ctid,proto3" json:"ctid,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // optional, preferred peer
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_cotune_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{5}
}

func (x *FetchRequest) GetCtid() string {
	if x != nil {
		return x.Ctid
	}
	return ""
}

func (x *FetchRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *FetchRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

type ShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,4,opt,name=artist,proto3" json:"artist,omitempty"`
	Recognized    bool                   `protobuf:"varint,5,opt,name=recognized,proto3" json:"recognized,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"` // legacy, deprecated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareRequest) Reset() {
	*x = ShareRequest{}
	mi := &file_cotune_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRequest) ProtoMessage() {}

func (x *ShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRequest.ProtoReflect.Descriptor instead.
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{6}
}

func (x *ShareRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *ShareRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShareRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShareRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *ShareRequest) GetRecognized() bool {
	if x != nil {
		return x.Recognized
	}
	return false
}

func (x *ShareRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type AnnounceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	mi := &file_cotune_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{7}
}

type RelaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaysRequest) Reset() {
	*x = RelaysRequest{}
	mi := &file_cotune_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaysRequest) ProtoMessage() {}

func (x *RelaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaysRequest.ProtoReflect.Descriptor instead.
func (*RelaysRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{8}
}

type RelayEnableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEnableRequest) Reset() {
	*x = RelayEnableRequest{}
	mi := &file_cotune_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEnableRequest) ProtoMessage() {}

func (x *RelayEnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEnableRequest.ProtoReflect.Descriptor instead.
func (*RelayEnableRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{9}
}

type RelayRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequestRequest) Reset() {
	*x = RelayRequestRequest{}
	mi := &file_cotune_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequestRequest) ProtoMessage() {}

func (x *RelayRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequestRequest.ProtoReflect.Descriptor instead.
func (*RelayRequestRequest) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{10}
}

func (x *RelayRequestRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// Response messages
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_cotune_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_cotune_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{12}
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type PeerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerInfo      *PeerInfo              `protobuf:"bytes,1,opt,name=peer_info,json=peerInfo,proto3" json:"peer_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfoResponse) Reset() {
	*x = PeerInfoResponse{}
	mi := &file_cotune_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoResponse) ProtoMessage() {}

func (x *PeerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoResponse.ProtoReflect.Descriptor instead.
func (*PeerInfoResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{13}
}

func (x *PeerInfoResponse) GetPeerInfo() *PeerInfo {
	if x != nil {
		return x.PeerInfo
	}
	return nil
}

type KnownPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownPeersResponse) Reset() {
	*x = KnownPeersResponse{}
	mi := &file_cotune_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownPeersResponse) ProtoMessage() {}

func (x *KnownPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownPeersResponse.ProtoReflect.Descriptor instead.
func (*KnownPeersResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{14}
}

func (x *KnownPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_cotune_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{15}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctid          string                 `protobuf:"bytes,1,opt,name=ctid,proto3" json:"ctid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Recognized    bool                   `protobuf:"varint,4,opt,name=recognized,proto3" json:"recognized,omitempty"`
	Providers     []string               `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_cotune_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{16}
}

func (x *SearchResult) GetCtid() string {
	if x != nil {
		return x.Ctid
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *SearchResult) GetRecognized() bool {
	if x != nil {
		return x.Recognized
	}
	return false
}

func (x *SearchResult) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_cotune_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{17}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderIds   []string               `protobuf:"bytes,1,rep,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProvidersResponse) Reset() {
	*x = SearchProvidersResponse{}
	mi := &file_cotune_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProvidersResponse) ProtoMessage() {}

func (x *SearchProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProvidersResponse.ProtoReflect.Descriptor instead.
func (*SearchProvidersResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{18}
}

func (x *SearchProvidersResponse) GetProviderIds() []string {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_cotune_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{19}
}

func (x *FetchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareResponse) Reset() {
	*x = ShareResponse{}
	mi := &file_cotune_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareResponse) ProtoMessage() {}

func (x *ShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareResponse.ProtoReflect.Descriptor instead.
func (*ShareResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{20}
}

func (x *ShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShareResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AnnounceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceResponse) Reset() {
	*x = AnnounceResponse{}
	mi := &file_cotune_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceResponse) ProtoMessage() {}

func (x *AnnounceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceResponse.ProtoReflect.Descriptor instead.
func (*AnnounceResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{21}
}

func (x *AnnounceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RelaysResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelayAddresses []string               `protobuf:"bytes,1,rep,name=relay_addresses,json=relayAddresses,proto3" json:"relay_addresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelaysResponse) Reset() {
	*x = RelaysResponse{}
	mi := &file_cotune_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaysResponse) ProtoMessage() {}

func (x *RelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaysResponse.ProtoReflect.Descriptor instead.
func (*RelaysResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{22}
}

func (x *RelaysResponse) GetRelayAddresses() []string {
	if x != nil {
		return x.RelayAddresses
	}
	return nil
}

type RelayEnableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEnableResponse) Reset() {
	*x = RelayEnableResponse{}
	mi := &file_cotune_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEnableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEnableResponse) ProtoMessage() {}

func (x *RelayEnableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEnableResponse.ProtoReflect.Descriptor instead.
func (*RelayEnableResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{23}
}

func (x *RelayEnableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RelayRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequestResponse) Reset() {
	*x = RelayRequestResponse{}
	mi := &file_cotune_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequestResponse) ProtoMessage() {}

func (x *RelayRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cotune_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequestResponse.ProtoReflect.Descriptor instead.
func (*RelayRequestResponse) Descriptor() ([]byte, []int) {
	return file_cotune_proto_rawDescGZIP(), []int{24}
}

func (x *RelayRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RelayRequestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cotune_proto protoreflect.FileDescriptor

const file_cotune_proto_rawDesc = "" +
	"\n" +
	"\fcotune.proto\x12\x06cotune\"\x0f\n" +
	"\rStatusRequest\")\n" +
	"\x0fPeerInfoRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\"k\n" +
	"\x0eConnectRequest\x12\x1e\n" +
	"\tmultiaddr\x18\x01 \x01(\tH\x00R\tmultiaddr\x12/\n" +
	"\tpeer_info\x18\x02 \x01(\v2\x10.cotune.PeerInfoH\x00R\bpeerInfoB\b\n" +
	"\x06target\"F\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\x05R\n" +
	"maxResults\">\n" +
	"\x16SearchProvidersRequest\x12\x12\n" +
	"\x04ctid\x18\x01 \x01(\tR\x04ctid\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"\\\n" +
	"\fFetchRequest\x12\x12\n" +
	"\x04ctid\x18\x01 \x01(\tR\x04ctid\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\"\xa7\x01\n" +
	"\fShareRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x04 \x01(\tR\x06artist\x12\x1e\n" +
	"\n" +
	"recognized\x18\x05 \x01(\bR\n" +
	"recognized\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\"\x11\n" +
	"\x0fAnnounceRequest\"\x0f\n" +
	"\rRelaysRequest\"\x14\n" +
	"\x12RelayEnableRequest\".\n" +
	"\x13RelayRequestRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"D\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"A\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\"A\n" +
	"\x10PeerInfoResponse\x12-\n" +
	"\tpeer_info\x18\x01 \x01(\v2\x10.cotune.PeerInfoR\bpeerInfo\"<\n" +
	"\x12KnownPeersResponse\x12&\n" +
	"\x05peers\x18\x01 \x03(\v2\x10.cotune.PeerInfoR\x05peers\"A\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8e\x01\n" +
	"\fSearchResult\x12\x12\n" +
	"\x04ctid\x18\x01 \x01(\tR\x04ctid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x1e\n" +
	"\n" +
	"recognized\x18\x04 \x01(\bR\n" +
	"recognized\x12\x1c\n" +
	"\tproviders\x18\x05 \x03(\tR\tproviders\"@\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.cotune.SearchResultR\aresults\"<\n" +
	"\x17SearchProvidersResponse\x12!\n" +
	"\fprovider_ids\x18\x01 \x03(\tR\vproviderIds\"S\n" +
	"\rFetchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"S\n" +
	"\rShareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\x10AnnounceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x0eRelaysResponse\x12'\n" +
	"\x0frelay_addresses\x18\x01 \x03(\tR\x0erelayAddresses\"/\n" +
	"\x13RelayEnableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x14RelayRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x88\x06\n" +
	"\rCotuneService\x127\n" +
	"\x06Status\x12\x15.cotune.StatusRequest\x1a\x16.cotune.StatusResponse\x12=\n" +
	"\bPeerInfo\x12\x17.cotune.PeerInfoRequest\x1a\x18.cotune.PeerInfoResponse\x12?\n" +
	"\n" +
	"KnownPeers\x12\x15.cotune.StatusRequest\x1a\x1a.cotune.KnownPeersResponse\x12:\n" +
	"\aConnect\x12\x16.cotune.ConnectRequest\x1a\x17.cotune.ConnectResponse\x127\n" +
	"\x06Search\x12\x15.cotune.SearchRequest\x1a\x16.cotune.SearchResponse\x12R\n" +
	"\x0fSearchProviders\x12\x1e.cotune.SearchProvidersRequest\x1a\x1f.cotune.SearchProvidersResponse\x124\n" +
	"\x05Fetch\x12\x14.cotune.FetchRequest\x1a\x15.cotune.FetchResponse\x124\n" +
	"\x05Share\x12\x14.cotune.ShareRequest\x1a\x15.cotune.ShareResponse\x12=\n" +
	"\bAnnounce\x12\x17.cotune.AnnounceRequest\x1a\x18.cotune.AnnounceResponse\x127\n" +
	"\x06Relays\x12\x15.cotune.RelaysRequest\x1a\x16.cotune.RelaysResponse\x12F\n" +
	"\vRelayEnable\x12\x1a.cotune.RelayEnableRequest\x1a\x1b.cotune.RelayEnableResponse\x12I\n" +
	"\fRelayRequest\x12\x1b.cotune.RelayRequestRequest\x1a\x1c.cotune.RelayRequestResponseB(Z&github.com/cotune/go-backend/api/protob\x06proto3"

var (
	file_cotune_proto_rawDescOnce sync.Once
	file_cotune_proto_rawDescData []byte
)

func file_cotune_proto_rawDescGZIP() []byte {
	file_cotune_proto_rawDescOnce.Do(func() {
		file_cotune_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cotune_proto_rawDesc), len(file_cotune_proto_rawDesc)))
	})
	return file_cotune_proto_rawDescData
}

var file_cotune_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_cotune_proto_goTypes = []any{
	(*StatusRequest)(nil),           // 0: cotune.StatusRequest
	(*PeerInfoRequest)(nil),         // 1: cotune.PeerInfoRequest
	(*ConnectRequest)(nil),          // 2: cotune.ConnectRequest
	(*SearchRequest)(nil),           // 3: cotune.SearchRequest
	(*SearchProvidersRequest)(nil),  // 4: cotune.SearchProvidersRequest
	(*FetchRequest)(nil),            // 5: cotune.FetchRequest
	(*ShareRequest)(nil),            // 6: cotune.ShareRequest
	(*AnnounceRequest)(nil),         // 7: cotune.AnnounceRequest
	(*RelaysRequest)(nil),           // 8: cotune.RelaysRequest
	(*RelayEnableRequest)(nil),      // 9: cotune.RelayEnableRequest
	(*RelayRequestRequest)(nil),     // 10: cotune.RelayRequestRequest
	(*StatusResponse)(nil),          // 11: cotune.StatusResponse
	(*PeerInfo)(nil),                // 12: cotune.PeerInfo
	(*PeerInfoResponse)(nil),        // 13: cotune.PeerInfoResponse
	(*KnownPeersResponse)(nil),      // 14: cotune.KnownPeersResponse
	(*ConnectResponse)(nil),         // 15: cotune.ConnectResponse
	(*SearchResult)(nil),            // 16: cotune.SearchResult
	(*SearchResponse)(nil),          // 17: cotune.SearchResponse
	(*SearchProvidersResponse)(nil), // 18: cotune.SearchProvidersResponse
	(*FetchResponse)(nil),           // 19: cotune.FetchResponse
	(*ShareResponse)(nil),           // 20: cotune.ShareResponse
	(*AnnounceResponse)(nil),        // 21: cotune.AnnounceResponse
	(*RelaysResponse)(nil),          // 22: cotune.RelaysResponse
	(*RelayEnableResponse)(nil),     // 23: cotune.RelayEnableResponse
	(*RelayRequestResponse)(nil),    // 24: cotune.RelayRequestResponse
}
var file_cotune_proto_depIdxs = []int32{
	12, // 0: cotune.ConnectRequest.peer_info:type_name -> cotune.PeerInfo
	12, // 1: cotune.PeerInfoResponse.peer_info:type_name -> cotune.PeerInfo
	12, // 2: cotune.KnownPeersResponse.peers:type_name -> cotune.PeerInfo
	16, // 3: cotune.SearchResponse.results:type_name -> cotune.SearchResult
	0,  // 4: cotune.CotuneService.Status:input_type -> cotune.StatusRequest
	1,  // 5: cotune.CotuneService.PeerInfo:input_type -> cotune.PeerInfoRequest
	0,  // 6: cotune.CotuneService.KnownPeers:input_type -> cotune.StatusRequest
	2,  // 7: cotune.CotuneService.Connect:input_type -> cotune.ConnectRequest
	3,  // 8: cotune.CotuneService.Search:input_type -> cotune.SearchRequest
	4,  // 9: cotune.CotuneService.SearchProviders:input_type -> cotune.SearchProvidersRequest
	5,  // 10: cotune.CotuneService.Fetch:input_type -> cotune.FetchRequest
	6,  // 11: cotune.CotuneService.Share:input_type -> cotune.ShareRequest
	7,  // 12: cotune.CotuneService.Announce:input_type -> cotune.AnnounceRequest
	8,  // 13: cotune.CotuneService.Relays:input_type -> cotune.RelaysRequest
	9,  // 14: cotune.CotuneService.RelayEnable:input_type -> cotune.RelayEnableRequest
	10, // 15: cotune.CotuneService.RelayRequest:input_type -> cotune.RelayRequestRequest
	11, // 16: cotune.CotuneService.Status:output_type -> cotune.StatusResponse
	13, // 17: cotune.CotuneService.PeerInfo:output_type -> cotune.PeerInfoResponse
	14, // 18: cotune.CotuneService.KnownPeers:output_type -> cotune.KnownPeersResponse
	15, // 19: cotune.CotuneService.Connect:output_type -> cotune.ConnectResponse
	17, // 20: cotune.CotuneService.Search:output_type -> cotune.SearchResponse
	18, // 21: cotune.CotuneService.SearchProviders:output_type -> cotune.SearchProvidersResponse
	19, // 22: cotune.CotuneService.Fetch:output_type -> cotune.FetchResponse
	20, // 23: cotune.CotuneService.Share:output_type -> cotune.ShareResponse
	21, // 24: cotune.CotuneService.Announce:output_type -> cotune.AnnounceResponse
	22, // 25: cotune.CotuneService.Relays:output_type -> cotune.RelaysResponse
	23, // 26: cotune.CotuneService.RelayEnable:output_type -> cotune.RelayEnableResponse
	24, // 27: cotune.CotuneService.RelayRequest:output_type -> cotune.RelayRequestResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cotune_proto_init() }
func file_cotune_proto_init() {
	if File_cotune_proto != nil {
		return
	}
	file_cotune_proto_msgTypes[2].OneofWrappers = []any{
		(*ConnectRequest_Multiaddr)(nil),
		(*ConnectRequest_PeerInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cotune_proto_rawDesc), len(file_cotune_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cotune_proto_goTypes,
		DependencyIndexes: file_cotune_proto_depIdxs,
		MessageInfos:      file_cotune_proto_msgTypes,
	}.Build()
	File_cotune_proto = out.File
	file_cotune_proto_goTypes = nil
	file_cotune_proto_depIdxs = nil
}
