// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: cotune.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CotuneService_Status_FullMethodName          = "/cotune.CotuneService/Status"
	CotuneService_PeerInfo_FullMethodName        = "/cotune.CotuneService/PeerInfo"
	CotuneService_KnownPeers_FullMethodName      = "/cotune.CotuneService/KnownPeers"
	CotuneService_Connect_FullMethodName         = "/cotune.CotuneService/Connect"
	CotuneService_Search_FullMethodName          = "/cotune.CotuneService/Search"
	CotuneService_SearchProviders_FullMethodName = "/cotune.CotuneService/SearchProviders"
	CotuneService_Fetch_FullMethodName           = "/cotune.CotuneService/Fetch"
	CotuneService_Share_FullMethodName           = "/cotune.CotuneService/Share"
	CotuneService_Announce_FullMethodName        = "/cotune.CotuneService/Announce"
	CotuneService_Relays_FullMethodName          = "/cotune.CotuneService/Relays"
	CotuneService_RelayEnable_FullMethodName     = "/cotune.CotuneService/RelayEnable"
	CotuneService_RelayRequest_FullMethodName    = "/cotune.CotuneService/RelayRequest"
)

// CotuneServiceClient is the client API for CotuneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main IPC service
type CotuneServiceClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	PeerInfo(ctx context.Context, in *PeerInfoRequest, opts ...grpc.CallOption) (*PeerInfoResponse, error)
	KnownPeers(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*KnownPeersResponse, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchProviders(ctx context.Context, in *SearchProvidersRequest, opts ...grpc.CallOption) (*SearchProvidersResponse, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*AnnounceResponse, error)
	Relays(ctx context.Context, in *RelaysRequest, opts ...grpc.CallOption) (*RelaysResponse, error)
	RelayEnable(ctx context.Context, in *RelayEnableRequest, opts ...grpc.CallOption) (*RelayEnableResponse, error)
	RelayRequest(ctx context.Context, in *RelayRequestRequest, opts ...grpc.CallOption) (*RelayRequestResponse, error)
}

type cotuneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCotuneServiceClient(cc grpc.ClientConnInterface) CotuneServiceClient {
	return &cotuneServiceClient{cc}
}

func (c *cotuneServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CotuneService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) PeerInfo(ctx context.Context, in *PeerInfoRequest, opts ...grpc.CallOption) (*PeerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerInfoResponse)
	err := c.cc.Invoke(ctx, CotuneService_PeerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) KnownPeers(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*KnownPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnownPeersResponse)
	err := c.cc.Invoke(ctx, CotuneService_KnownPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, CotuneService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, CotuneService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) SearchProviders(ctx context.Context, in *SearchProvidersRequest, opts ...grpc.CallOption) (*SearchProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProvidersResponse)
	err := c.cc.Invoke(ctx, CotuneService_SearchProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, CotuneService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareResponse)
	err := c.cc.Invoke(ctx, CotuneService_Share_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*AnnounceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceResponse)
	err := c.cc.Invoke(ctx, CotuneService_Announce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) Relays(ctx context.Context, in *RelaysRequest, opts ...grpc.CallOption) (*RelaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelaysResponse)
	err := c.cc.Invoke(ctx, CotuneService_Relays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) RelayEnable(ctx context.Context, in *RelayEnableRequest, opts ...grpc.CallOption) (*RelayEnableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayEnableResponse)
	err := c.cc.Invoke(ctx, CotuneService_RelayEnable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cotuneServiceClient) RelayRequest(ctx context.Context, in *RelayRequestRequest, opts ...grpc.CallOption) (*RelayRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayRequestResponse)
	err := c.cc.Invoke(ctx, CotuneService_RelayRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CotuneServiceServer is the server API for CotuneService service.
// All implementations must embed UnimplementedCotuneServiceServer
// for forward compatibility.
//
// Main IPC service
type CotuneServiceServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	PeerInfo(context.Context, *PeerInfoRequest) (*PeerInfoResponse, error)
	KnownPeers(context.Context, *StatusRequest) (*KnownPeersResponse, error)
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchProviders(context.Context, *SearchProvidersRequest) (*SearchProvidersResponse, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	Share(context.Context, *ShareRequest) (*ShareResponse, error)
	Announce(context.Context, *AnnounceRequest) (*AnnounceResponse, error)
	Relays(context.Context, *RelaysRequest) (*RelaysResponse, error)
	RelayEnable(context.Context, *RelayEnableRequest) (*RelayEnableResponse, error)
	RelayRequest(context.Context, *RelayRequestRequest) (*RelayRequestResponse, error)
	mustEmbedUnimplementedCotuneServiceServer()
}

// UnimplementedCotuneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCotuneServiceServer struct{}

func (UnimplementedCotuneServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedCotuneServiceServer) PeerInfo(context.Context, *PeerInfoRequest) (*PeerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeerInfo not implemented")
}
func (UnimplementedCotuneServiceServer) KnownPeers(context.Context, *StatusRequest) (*KnownPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KnownPeers not implemented")
}
func (UnimplementedCotuneServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCotuneServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCotuneServiceServer) SearchProviders(context.Context, *SearchProvidersRequest) (*SearchProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchProviders not implemented")
}
func (UnimplementedCotuneServiceServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedCotuneServiceServer) Share(context.Context, *ShareRequest) (*ShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Share not implemented")
}
func (UnimplementedCotuneServiceServer) Announce(context.Context, *AnnounceRequest) (*AnnounceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Announce not implemented")
}
func (UnimplementedCotuneServiceServer) Relays(context.Context, *RelaysRequest) (*RelaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Relays not implemented")
}
func (UnimplementedCotuneServiceServer) RelayEnable(context.Context, *RelayEnableRequest) (*RelayEnableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayEnable not implemented")
}
func (UnimplementedCotuneServiceServer) RelayRequest(context.Context, *RelayRequestRequest) (*RelayRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayRequest not implemented")
}
func (UnimplementedCotuneServiceServer) mustEmbedUnimplementedCotuneServiceServer() {}
func (UnimplementedCotuneServiceServer) testEmbeddedByValue()                       {}

// UnsafeCotuneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CotuneServiceServer will
// result in compilation errors.
type UnsafeCotuneServiceServer interface {
	mustEmbedUnimplementedCotuneServiceServer()
}

func RegisterCotuneServiceServer(s grpc.ServiceRegistrar, srv CotuneServiceServer) {
	// If the following call panics, it indicates UnimplementedCotuneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CotuneService_ServiceDesc, srv)
}

func _CotuneService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_PeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).PeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_PeerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).PeerInfo(ctx, req.(*PeerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_KnownPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).KnownPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_KnownPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).KnownPeers(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_SearchProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).SearchProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_SearchProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).SearchProviders(ctx, req.(*SearchProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_Share_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).Share(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_Share_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).Share(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_Announce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).Announce(ctx, req.(*AnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_Relays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).Relays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_Relays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).Relays(ctx, req.(*RelaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_RelayEnable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayEnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).RelayEnable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_RelayEnable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).RelayEnable(ctx, req.(*RelayEnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CotuneService_RelayRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CotuneServiceServer).RelayRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CotuneService_RelayRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CotuneServiceServer).RelayRequest(ctx, req.(*RelayRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CotuneService_ServiceDesc is the grpc.ServiceDesc for CotuneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CotuneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cotune.CotuneService",
	HandlerType: (*CotuneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _CotuneService_Status_Handler,
		},
		{
			MethodName: "PeerInfo",
			Handler:    _CotuneService_PeerInfo_Handler,
		},
		{
			MethodName: "KnownPeers",
			Handler:    _CotuneService_KnownPeers_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _CotuneService_Connect_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _CotuneService_Search_Handler,
		},
		{
			MethodName: "SearchProviders",
			Handler:    _CotuneService_SearchProviders_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _CotuneService_Fetch_Handler,
		},
		{
			MethodName: "Share",
			Handler:    _CotuneService_Share_Handler,
		},
		{
			MethodName: "Announce",
			Handler:    _CotuneService_Announce_Handler,
		},
		{
			MethodName: "Relays",
			Handler:    _CotuneService_Relays_Handler,
		},
		{
			MethodName: "RelayEnable",
			Handler:    _CotuneService_RelayEnable_Handler,
		},
		{
			MethodName: "RelayRequest",
			Handler:    _CotuneService_RelayRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cotune.proto",
}
